name: weath
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.9
  http: ^0.13.4
  provider: ^6.0.1
  json_serializable: ^6.1.0
  json_annotation: ^4.4.0
  searchfield: ^0.5.6
  smooth_page_indicator: 
  weather_icons: ^3.0.0
  fluttertoast: ^8.0.8
  carousel_slider: ^4.0.0
  
  # smooth_page_indicator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
 
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
  - assets/images/

  